[project]
authors = ["Kostusas <kostasvilkelis@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "spatial_vegetation"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
rasterio = ">=1.4.3,<2"
python = ">=3.12.8,<4"
numpy = ">=2.2.1,<3"
ipykernel = ">=6.29.5,<7"
matplotlib = ">=3.10.0,<4"
geopandas = ">=1.0.1,<2"
shapely = ">=2.0.6,<3"
requests = ">=2.32.3,<3"
fiona = ">=1.10.1,<2"
lxml = ">=5.3.0,<6"
