[project]
authors = ["Kostusas <kostasvilkelis@gmail.com>"]
channels = ["conda-forge"]
description = "Spatial vegetation analysis tools"
name = "spatial_vegetation"
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
python = "3.9.*"
numpy = ">=2.0.2,<3"
ipykernel = ">=6.29.5,<7"
geopandas = ">=1.0.1,<2"
matplotlib = ">=3.9.4,<4"
lxml = ">=5.3.1,<6"
shapely = ">=2.0.7,<3"
requests = ">=2.32.3,<3"
jupyterlab = ">=4.3.6,<5"
jupyterlab-git = ">=0.51.0,<0.52"

[feature.conda.dependencies]
rasterio = "*"

# ECW feature uses custom wheel with ECW support
[feature.ecw.pypi-dependencies]
rasterio = { path = "./rasterio-1.5.0.dev0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl" }

[feature.ecw.activation.env]
GDAL_DATA = "$PIXI_PROJECT_ROOT/.pixi/envs/ecw/share/gdal"

# Task to set up GDAL data for ECW feature
[feature.ecw.tasks]
setup-ecw = """
mkdir -p "$PIXI_PROJECT_ROOT/.pixi/envs/ecw/share/gdal" && 
cp -r ./gdal_share/* "$PIXI_PROJECT_ROOT/.pixi/envs/ecw/share/gdal/" && 
echo "ECW environment ready with GDAL data"
"""

[environments]
ecw = ["ecw"]
conda = ["conda"]
